In [ ]:
import torch
y = torch.randint(1, 5, size=(3,4))
print(y)

tensor([[2, 4, 4, 3],
        [3, 3, 3, 2],
        [3, 2, 1, 4]])


In [ ]:
x = torch.randn(3)
print(x)

tensor([-0.7874,  0.1258,  0.9544])


In [ ]:
y = torch.randn(3)
print(y)

tensor([ 0.2336, -0.0703,  0.1762])


In [ ]:
ret = torch.mm(x,y) or x.mm(y)   #matrix multiplication
ret = torch.mv(x,y) or x.mv(y)   #matrix-vector multiplication
ret = torch.dot(x,y) or x.dot(y)   #dot product
ret = torch.t(x) or x.t()          #matrix transpose

tensor(-0.0246)


tensor([[-0.7333,  0.4283,  0.9697],
        [ 1.2080, -0.8636,  0.0088],
        [-1.0859, -0.3720, -0.0820],
        [ 0.3582, -1.3044, -0.1963]])

In [ ]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Linear(128,32)
    self.layer2 = nn.Linear(32,16)
    self.layer3 = nn.Linear(16,1)
  def forward(self,features):
    # if features are of shapes (8, 128)
    x = self.layer1(features)
    # (8,32)
    x = self.layer2(x)
    # (8,16)
    x = self.layer3(x)
    # (8,1)
    return x


In [ ]:
model = Model()
features = torch.randn(8,128)
model(features)
# Assume dataset1 and dataset2 are instances of a Dataset (or TensorDataset)
combined_dataset = ConcatDataset([dataset1, dataset2])

tensor([[-0.1380],
        [-0.0329],
        [-0.0719],
        [ 0.1655],
        [-0.2339],
        [ 0.6393],
        [-0.3688],
        [ 0.6643]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Linear(128,32)
    self.layer2 = nn.Linear(32,16)
    self.layer3 = nn.Linear(16,1)
  def forward(self,features):
    x = self.layer1(features)
    x = self.layer2(x)
    x = self.layer3(x)
    return x

device(type='cpu')

In [ ]:
import torch
import torch.nn as nn
m = nn.Conv1d(16,32,3,stride = 2,padding = 1)
input = torch.randn(20,16,50)
output = m(input)
print(output.shape)

torch.Size([20, 32, 25])


In [ ]:
import torch.autograd as autograd    #computation graph
from torch import Tensor             #tensor node in the computation graph
import torch.nn as nn                #neural networks
import torch.nn.functional as F      #layers, activations and more
import torch.optim as optim          #optimizers e.g. gradient descent, ADAM, etc.
from torch.jit import script, trace   #hybrid frontend decorator and tracing jit

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import pandas as pd
import json
import os

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

Hyperparameters

In [ ]:
learning_rate = 1e-5
batch_size = 8
num_workers = 2

Data Preprocessing

In [ ]:
# path of directory containing CSV files
path = '/home/sedrica/students/Vishal/final_dataset'

X_list = []
labels = []
voxel_ids = []

for file_name in os.listdir(path):
    if file_name.endswith('.json'):  # Check if file is a JSON file
        file_path = os.path.join(path, file_name)

        with open(file_path, 'r') as json_file:
            data = json.load(json_file)

        for item in data:
            voxel_id, X, label = item['voxel_id'], np.array(item['X']), item['label']
            if label != -1:
                X_list.append(X)
                labels.append(label)
                voxel_ids.append(voxel_id)

input_data = np.array(X_list)
output_data = np.array(labels)
print(input_data.shape)
print(output_data.shape)
print(len(voxel_ids))

train_data = torch.utils.data.TensorDataset(torch.tensor(input_data, dtype=torch.float32), torch.tensor(output_data, dtype=torch.long))
train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=num_workers, drop_last = True)


(2833, 20, 20, 20, 5)
(2833,)
2833


In [ ]:
for i, (inputs, labels) in enumerate(train_loader):
        print(inputs.shape)
        print(labels.shape)

# inputs = inputs.reshape((-1, 5,20,20,20))
# print(inputs.shape)
print(np.unique(output_data))
l = output_data[output_data == -1]
print (l)

torch.Size([8, 20, 20, 20, 5])
torch.Size([8])
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[]


Model

In [ ]:



class CNN3D(nn.Module):
    def __init__(self, channels = 5, num_classes = 20):
        super().__init__()
        self.BN3D1 = nn.BatchNorm3d(8)
        self.BN3D2 = nn.BatchNorm3d(64)
        self.BN3D3 = nn.BatchNorm3d(128)
        self.BN3D4 = nn.BatchNorm3d(256)
        self.BN3D5 = nn.BatchNorm3d(256)
        self.BN1D = nn.BatchNorm1d(256)
        self.conv_layer0 = nn.Conv3d(channels, 8, kernel_size=1, stride=1, bias=True)
        self.conv_layer1 = nn.Conv3d(8, 64, kernel_size=3, stride=1, bias=True)
        self.conv_layer2 = nn.Conv3d(64, 128, kernel_size=3, stride=1, bias=True)
        self.conv_layer3 = nn.Conv3d(128, 256, kernel_size=2, stride=1, bias=True)
        self.conv_layer4 = nn.Conv3d(256, 256, kernel_size=2, stride=1, bias=True)
        self.MaxPool = nn.MaxPool3d(kernel_size=2, stride=2, padding=1, ceil_mode=False)
        self.linear1 = nn.Linear(16384, 256)
        self.linear2 = nn.Linear(256, num_classes)
    def forward(self, x):
        x= self.BN3D1(self.conv_layer0(x))
        x = self.BN3D2(nn.ReLU()(self.conv_layer1(x)))
        x = self.BN3D3(self.MaxPool(nn.ReLU()(self.conv_layer2(x))))
        x = self.BN3D4(nn.ReLU()(self.conv_layer3(x)))
        x = self.BN3D5(self.MaxPool(nn.ReLU()(self.conv_layer4(x))))
        x = torch.flatten(x, 1)
        x = self.BN1D(nn.ReLU()(self.linear1(x)))
        x = self.linear2(x)
        return(x)

In [ ]:
model = CNN3D(channels = 5, num_classes = 20).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
#Define training loop:
num_epochs = 50
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(train_loader):
        inputs = inputs.to(device)
        labels = labels.to(device)
        inputs = inputs.reshape((-1,5,20,20,20))
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if (i+1) % 1 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, len(train_loader), loss.item()))

Epoch [1/50], Step [1/354], Loss: 1.2242
Epoch [1/50], Step [2/354], Loss: 0.2208
Epoch [1/50], Step [3/354], Loss: 1.5992
Epoch [1/50], Step [4/354], Loss: 0.2807
Epoch [1/50], Step [5/354], Loss: 0.0927
Epoch [1/50], Step [6/354], Loss: 0.3034
Epoch [1/50], Step [7/354], Loss: 0.1954
Epoch [1/50], Step [8/354], Loss: 0.4748
Epoch [1/50], Step [9/354], Loss: 0.9849
Epoch [1/50], Step [10/354], Loss: 0.3213
Epoch [1/50], Step [11/354], Loss: 0.7096
Epoch [1/50], Step [12/354], Loss: 1.2149
Epoch [1/50], Step [13/354], Loss: 0.2757
Epoch [1/50], Step [14/354], Loss: 0.1987
Epoch [1/50], Step [15/354], Loss: 0.2033
Epoch [1/50], Step [16/354], Loss: 0.1881
Epoch [1/50], Step [17/354], Loss: 0.2947
Epoch [1/50], Step [18/354], Loss: 0.2476
Epoch [1/50], Step [19/354], Loss: 0.1946
Epoch [1/50], Step [20/354], Loss: 0.1635
Epoch [1/50], Step [21/354], Loss: 0.1363
Epoch [1/50], Step [22/354], Loss: 1.8693
Epoch [1/50], Step [23/354], Loss: 0.4128
Epoch [1/50], Step [24/354], Loss: 0.1262
E